### ISSUE TITLE
Python 3: Execution of function definition

### ISSUE THREAD

**Issue by philipGaudreau** [michaelb/sniprun#113]
**Describe the bug**
When executing (reading) a function definition that has blank lines in it, an error occurs displaying:

```
RuntimeError:     <statement>
IndentationError: unexpected indent
```

**What do the bugs concerns? Sniprun itself, a particular interpreter?**
Using `Python3_fifo`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a python file.
2. Replicate the "Not working" example.
3. Select all.
4. Run (`:'<,'>SnipRun`).

**Expected behaviour**
Should interpret the whole function correctly.

**Example**
Working:
```python
def a():
    print("a")
    print("b")
```
Not Working:
```python
def a():
    print("a")

    print("b")
```

**Environment:**
 - Neovim version [e.g. v0.4.3]
 `NVIM v0.6.0-dev+550-g29cec32f4`
- OS/distribution
`20.04.2 LTS (GNU/Linux 5.4.0-71-generic x86_64)`
- if possible, GLIBC version (output of `ldd --version`)
`ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31`

**Additional context**

**Comment by michaelb** [comment]
Thanks for the report!

Actually, it's not just function definition, it's every indented bloc that wont work.

Interestingly enough, if instead the blank line contains a tab (for the correct indentation), it works; that must be why I didn't catch the test before.


It's probably due to Python3_fifo interpreting the empty line as a 'enter' command, and then a `Tab + print(...)` on its own is an indentation error

I think just removing every empty line except the last one would work...probably. I'll test later. What do you think?

**Comment by philipGaudreau** [comment]
Hi, thanks for the quick response :)

I agree with you that in this trivial example, the blank line could have been removed. However, in a more elaborated block of code, like:
```
def long_fn(...) -> ...:
    """
    Desc.

    Parameters
    ----------
    ...

    Returns
    -------
    ...
    """
    with open(...):
        ...

        for ... in ...:
            ...

            if cmd.run() != 0:
                ...

    ...

    return ...
```
, it is nice to have some space in between control flows.

**Comment by michaelb** [comment]
I meant, have Sniprun remove the blank lines from its copy of the visual selection before sending to the backend python interpreter, which doesn't really care.

**Comment by philipGaudreau** [comment]
Oh, I get what you mean now! Yes, it seems to makes sense to remove them before the process.
