### ISSUE TITLE
Persistent process

### ISSUE THREAD

**Issue by philipGaudreau** [michaelb/sniprun#117]
**Describe the bug**
The SnipRun process does not close by itself after buffer is closed / vim session is over.

**What do the bug concerns? Sniprun itself, a particular interpreter?**
Using `Python3_fifo`.

**Expected behavior**
Process should end when the buffer is closed.

**Screenshots**
![Screen Shot 2021-11-16 at 18 42 25](https://user-images.githubusercontent.com/22773951/142083845-9cd60358-f9b2-43ce-8e47-37564c1e6a65.png)

**Environment:**
 - Neovim version: `NVIM v0.6.0-dev+575-g2ef9d2a66`
- OS/distribution: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-71-generic x86_64)
- if possible, GLIBC version (output of `ldd --version`): (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31

**Additional context**
What is the proper way to end the SnipRun processes? I can add a `autocmd` if necessary.

**Comment by michaelb** [comment]
Nice catch!

There is quite a lot of them indeed, this is a mistake on my side and probably not something that can be solved cleanly via an autocmd.

I said 'cleanly' because there could be a way.... I'm at work right now so can't test but I *guess* that if you autocmd VimLeave to delete/close the pipe Python3_fifo uses to communicate (located at ~/.cache/sniprun/python3_fifo/xyz/ the associated process should be terminated.
The issue with this is that these files are shared between multiples vim instances for now, so this workaround will cause issues if you're using multiple sniprun from different neovim processes and quit one.



The fact is, I'm a little bit afraid to include
"kill $pid" in sniprun because any mismatch / error could kill a random process. Right now, the only mechanism is a timer that ends these processes ~10h after start, but I'll see what I can do to fix this behavior and try to push a new version sooner rather than later

**Comment by philipGaudreau** [comment]
Thanks for the fast answer!

> There is quite a lot of them indeed
Yes, and it was only a small sample! because I have an autocmd that runs SnipRun on `VimEnter` since I use `Python3_fifo` so it starts the kernel.

> VimLeave to delete/close the pipe Python3_fifo uses to communicate... The issue with this is that these files are shared between multiples vim instances for now, so this workaround will cause issues if you're using multiple sniprun from different neovim processes and quit one.
Yes, I usually use TMUX, so this is not really a good way for me haha.

> "kill $pid" in sniprun because any mismatch / error could kill a random process. Right now, the only mechanism is a timer that ends these processes ~10h after start.
Ok, that is what the `sleep 36000` is. Well at least they get terminated, but the other I didn't know why my computer was so slow and when I checked `htop`, I saw all CPUs maxed, idem with memory, so I flushed everything and it went back OK. And I guess that using a separate cache and flushing them individually would not be as efficient as it is not? As for the `kill $pid`, I  get what you mean, but a the same time, I don't know what could be wrong if it is done correctly (using `pidof` and friends). At the same time, how to keep track of which one to terminate if there is more than one due to multiple vim sessions...

**Comment by michaelb** [comment]
>  And I guess that using a separate cache 

Different background python instances for different neovim instances? That's what I have I mind to fix the issue

> flushing them individually would not be as efficient as it is now

Closing asynchronously one unique pipe ( thus closing the process) at VimLeave should be pretty cheap.


 > [kill pid....] I don't know what could be wrong if it is done correctly

I've done it (correctly, I hope) for the Mathematica interpreter, but while it was necessary, I consider this hack ugly and dangerous and would rather not do it again.


>  I saw all CPUs maxed, idem with memory

There must have been an *awful* lot of them or else you sniprun'd something alike an infinite loop

**Comment by michaelb** [comment]
Found the root cause of the issue, just have to fix this mess of pipes and files shared by sniprun's of different nvim instances

**Comment by michaelb** [comment]
Hey! the fix is up in v1.0.5!

the only downside of the current approach is that the background processes will keep running as long as one nvim process is running. 

I could probably do something better now I've got some access to each neovim process PID, but the `pkill -p $$` that kills the current script (and its children, among whose the python interpreter) that gets triggered when there is no any more 'nvim' process running looks safer at first glance

**Comment by philipGaudreau** [comment]
>the only downside of the current approach is that the background processes will keep running as long as one nvim process is running.

It is a huge step forward still!

**Comment by michaelb** [comment]
Indeed 

If you feel v1.0.5 is good enough, feel free to close this issue.... Or elaborate if it isn't 😉

**Comment by philipGaudreau** [comment]
Yes, I will try it this way and if problems with performance are still an issue, I will open another ticket.

Thank you for taking the time to fix it :)
