### ISSUE TITLE
Found a bug when running python code in REPL mode.

### ISSUE THREAD

**Issue by allencho1222** [michaelb/sniprun#136]
**Describe the bug**
For the error code line, `:SnipRun` notifies success.

**What do the bug concerns? Sniprun itself, a particular interpreter?**
I don't know where the bug originates.

**To Reproduce**
1. Create a python script with following statements:
```
a = 3
print(5)
print(4)
print(b)
```

2. Run `:SnipRun` over the `print(b)`. It will notify an error has happened.
3. Run `:SnipRun` again over the same line (`print(b)`). Now, It will notify success and **print** `3`, which is wrong.

**Expected behavior**
Error message has to occur whenever `:SnipRun` runs over `print(b)`.

**Environment:**
 - Neovim version: NVIM v0.7.0-dev+779-g8c720f6b9
- OS/distribution: MacOS (with python 3.9.9)
- SnipRun config:
```
repl_enable = { 'Python3_original', 'Lua_original' },
display = { "Classic", "VirtualTextOK", "NvimNotify"}
```

**Comment by michaelb** [comment]
Well that's quite a funky bug

We have quite different setup, I'm on neovim 0.6.1 and Arch-based linux, and no means (or will) to reproduce exactly

And unfortunately, I'm unable to reproduce this bug here, it spams consistently `NameError: name 'b' is not defined` just as expected. 

Could you:

- share here the log file after opening a problematic script and running sniprun just enough times to showcase the issue ? (It should be located at `$XDG_CACHE/sniprun/sniprun.log` or `$HOME/.cache/sniprun/sniprun.log`. Some  information, such as contents of other parts of the script may appear there.
- check if the same issue arises when another python interpreter is selected in sniprun' config (Python3_fifo for example)

Thanks for the bug report

**Comment by allencho1222** [comment]
Thank you for the reply.

To answer your request:

1. I attach the log file after running `:SnipRun` twice over the `print(b)`
[sniprun.log](https://github.com/michaelb/sniprun/files/7834947/sniprun.log)

2. I used `Python3_fifo` instead of `Python3_original` and `Python3_fifo` correctly works as I expected.

**Comment by michaelb** [comment]
Ok, still no luck on my end (to reproduce), I think our setups are too different

At least I can confirm it's neovim-master +sniprun+python+klepto (a python module) that together are doing crazy stuff...

Short story long, I probably won't be able to fix this... Maybe a passing neovim or python update will correct it if it's a bug on their end.
If it's not too bothersome for you, the workaround would probably to switch to Python3_fifo, it's better on some aspects but it has its fair share of issues which you may or may not encounter.


By curiosity, does it always print "3" or if you set like a = 19 or a = lambda x:x*2 it changes to something else?

**Comment by allencho1222** [comment]
Interestingly, it still prints `3` whatever `a` is.

I changed `a` to some values except 3 and removed `a`. But `:SnipRun` still shows 3.

I think that wrong behavior is not caused by `a` itself.
