### ISSUE TITLE
Process failed to start

### ISSUE THREAD

**Issue by iktefish** [michaelb/sniprun#137]
**Describe the bug**
I've installed the plugin using Packer and had it run `install.sh` just as the documentation said but whenever I try and execute
any piece of code using SnipRun, the following error occurrs.

**What do the bug concerns? SnipRun itself, a particular interpreter?**
The bug seems to stem from SnipRun itself as far as I can tell.

**To Reproduce**
1. Install SnipRun
2. Execute some Rust code

**Expected behavior**
Expected execution of the code snipped tried.

**Screenshots**
![Screenshot from 2022-01-17 13-10-49](https://user-images.githubusercontent.com/87042742/149725103-5f91cd7c-ae36-48c9-840b-fa362ba56528.png)

**Environment:**
 - Neovim version:
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/1gpfwjr4rm2hw4jcb226m3nj9rf5sayq-neovim-unwrapped-0.6.1/share/nvim
"
```

- OS/distribution:
  - NixOS
- GNU libc version:
```
ldd (GNU libc) 2.33
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Additional context**
I checked `/home/iktefish/.local/share/nvim/site/pack/packer/start/sniprun/target/release` to see if the binary is present,
and it looks like it is (shown in screenshot).
![Screenshot from 2022-01-17 13-20-02](https://user-images.githubusercontent.com/87042742/149725755-752470c6-7caf-45e2-aeb2-1da8480a5bb0.png)

**Comment by michaelb** [comment]
Maybe `:checkhealth snipun` will get us some more info, but I remember vaguely some other user said he had to do something special for NixOS (using the BuildRustPackage ....? or someting. I know close to nothing about nix. Relevant issue is #107 , but the link is broken)

Hope that can help

**Comment by nyngwang** [comment]
> Maybe :checkhealth snipun will get us some more info

@michaelb :/

<img src="https://user-images.githubusercontent.com/24765272/149749019-aae34cfc-bdfc-4e4d-ae68-9dfaf06c5965.png" width="700">

**Comment by michaelb** [comment]
`checkhealth sniprun` (typo)

**Comment by michaelb** [comment]
Just saw the Apple logo, are you on Mac?

MacOS users needs to recompile sniprun themselves, and it's a long shot, but if you have an ARM CPU, this applies too even if you're on *nix

**Comment by nyngwang** [comment]
OK i didn't notice it's a typo too. I'm reinstalling it

**Comment by nyngwang** [comment]
@michaelb: The `'<,'>SnipRun` always got result `Compile-time error:` and nothing shown :/

**Comment by michaelb** [comment]
I'll need more info to help you; could you provide: 

- output of `:checkhealth sniprun` without the typo from earlier

- whether a simpler thing works : 
1. a `println!("yay");` in a rust file (without fn main().....
2. a println!("yay"); in a markdown file, embbeded in a rust code block

- the log file ($HOME/.cache/sniprun/sniprun.log) after a single sniprun that showcases the failure

(I may have some ideas: it's possible the entry point detection is broken through a markdown)

**Comment by nyngwang** [comment]
@michaelb Nothing shown with this setup.

![image](https://user-images.githubusercontent.com/24765272/149756756-b461f35e-be21-4dca-85e9-88af4a74d49d.png)
![image](https://user-images.githubusercontent.com/24765272/149756637-bca18efc-2a96-435c-93b2-02f2f9b7eacb.png)
![image](https://user-images.githubusercontent.com/24765272/149756671-9873fcc5-ec99-445b-a8fa-597a888cbe58.png)

**Comment by nyngwang** [comment]
@michaelb  It doesn't output anything with this configuration. Even the `Compile-time error:` is not shown :(

**Comment by michaelb** [comment]
Maybe the $XDG_CACHE is different on your system?

Passing the checkhealth _should_ mean the Rust backend works (and thus creates a log file), but just in case, could you try to recompile locally?
 (by using
`'bash ./install.sh 1'` 
in packer & reinstalling, the '1' is not a typo)

Usually very weird issues come from this kind of stuff, but without the log file, i'm a bit stuck; its absence usually means the sniprun binary I provide is incompatible with your OS/CPU architecture, but it looked like something ran fine earlier...

**Comment by nyngwang** [comment]
I'm using zsh, and I put my `.zshrc` under ``./config/zsh/`,  is this related?

**Comment by iktefish** [comment]
@michaelb Running `:checkhealth sniprun` outouts this:
![Screenshot from 2022-01-17 22-26-40](https://user-images.githubusercontent.com/87042742/149806731-38b294a6-ffb6-4851-8ddd-9215f15f5d04.png)

**Comment by michaelb** [comment]
If your config was already including the `bash ./install.sh 1` this time around, this means the script wasn't even able to compile sniprun into an executable.

So that's starting to look bad.

What if you 
`cd ~/.local/share...../pack/sniprun/` and run
`cargo build --release` ?

That should give us the answer

**Comment by iktefish** [comment]
Amazing catch, `bash ./install.sh` failed to compile SnipRun, now I got what went wrong.

For anyone facing this problem in the future:
If you only have `nixpkgs.rustc` `nixpkgs.cargo` installed in a dev-shell on a per-project basis rather than having it installed system wide, the script won't be able to compile the bin. Run the script from a dev-shell that has the required packages or install the packages system wide, I tried both just now and both worked.

@michaelb Btw sir, awesome plugin!

**Comment by michaelb** [comment]
Wonderful, i'll leave a note up in the doc so future users can avoid so much trouble

Thank you for the patient debugging, I hope the experience will be better from now on (though, sniprun has its set off limitations😅), and feel free to close this issue

**Comment by j-hui** [comment]
Just ran into this issue myself, and wanted to follow up on this:

> I remember vaguely some other user said he had to do something special for NixOS (using the BuildRustPackage ....? or someting. I know close to nothing about nix. 

Guided by [this helpful SO answer](https://unix.stackexchange.com/questions/522822/different-methods-to-run-a-non-nixos-executable-on-nixos), here is what I found.

The reason we get this weird "file not found" error on NixOS is because NixOS places everything in non-standard locations. In particualr, the pre-built sniprun binary is looking for the loader at `/lib64/ld-linux-x86-64.so.2`, but NixOS does not have that installed there:

```
$ ldd sniprun
	linux-vdso.so.1 (0x00007ffed70a8000)
	libgcc_s.so.1 => /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libgcc_s.so.1 (0x00007f1c86c84000)
	libpthread.so.0 => /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libpthread.so.0 (0x00007f1c86c63000)
	libdl.so.2 => /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libdl.so.2 (0x00007f1c86c5e000)
	libc.so.6 => /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib/libc.so.6 (0x00007f1c86a9d000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/nprym6lf8lzhp1irb42lb4vp8069l5rj-glibc-2.32-54/lib64/ld-linux-x86-64.so.2 (0x00007f1c86e2e000)
$ ls /lib64/
ls: cannot access '/lib64/': No such file or directory
```

So `sniprun` fails to execute because the OS is unable to find its loader:

```
$ ./sniprun
Failed to execute process './sniprun'. Reason:
The file './sniprun' does not exist or could not be executed.
```

This should be true for all NixOS users, meaning it is probably not possible to use the pre-built `sniprun` binary without some binary patching.

I'm still looking for a workaround that doesn't involve compiling `sniprun` from source (it takes a little while), but haven't found anything that's very stable. In particular, I can successfully execute the pre-built `sniprun` after I patch it with `patchelf --set-interpreter <any-ld.so.2> ./sniprun` , but it's not clear to me which loader I should use (there are 29 installed on my current system xD), and all of them may be garbage-collected when I upgrade my system (as noted in the SO answer). So perhaps this is a dead-end, but I wanted to leave a trail in case anyone else picks up from here.

**Comment by michaelb** [comment]
Clearly not in my expertise field, but I remember having another user a while ago who created a script for NixOS with a tool they called BuildRustPackage (though that involved compiling sniprun), but they deleted their nvim-config repo before I had a chance to copy that here

patchelf sounds like the right tool for the job, do you have a way to dynamically get the path to neovim's `ld` (`ldd $(which neovim)`) ? (Though I'm not 100% sure neovim needs ld since it's quite self-contained)
