### ISSUE TITLE
display in terminal not perfect

### ISSUE THREAD

**Issue by qvieth** [michaelb/sniprun#156]
**Describe the bug**

the line OK and ERROR in the terminal it went like this

``` 
  ------------------OK-----------------
----
> a=1
> b=2
> print(a)
   ------------------ERROR-----------------
----
> print(a)
```

expected result:
```
   ------------------OK-----------------
> a=1
> b=2
> print(a)
   ------------------ERROR-----------------
> print(a)
```
**Screenshots**
![image](https://user-images.githubusercontent.com/71810726/167298096-0c158fd2-5887-416a-ab10-9c0507b29b75.png)

**Environment:**
- Neovim version [e.g. v0.8.0]
- OS: fedora 35
- if possible, GLIBC version (output of `ldd --version`): ldd (GNU libc) 2.34

**Comment by qvieth** [comment]
![image](https://user-images.githubusercontent.com/71810726/167436787-e88c1c86-0f94-46be-8fa6-78de15ac5112.png)

![image](https://user-images.githubusercontent.com/71810726/167437060-d7e45d3b-4034-4cfe-b932-7cd5b2079163.png)

Gutter do you mean this line? I could see it provides code diagnostics symbols.

I'm using LunarVim which provide a default with many already set up plugins. [Here](https://www.lunarvim.org/plugins/01-core-plugins-list.html) is a full list of its default plugins.

From this list I can make a guess the gutter is from null-ls tho.

**Comment by michaelb** [comment]
Actually went to null-lsp repo and opened an issue for nothing; I noticed after the fact that the `signcolumn` option was responsible for the gutter.
But that is not the end of the story, because I'm still able to have this ugly ---- line-wrapping.

For now a solution will be to reduce the width of the ----s , since the line didn't touch any border (left because of signcolumn, right for obsucre reasons to begin with, I'm not against making the next release include a less wide ----

**Comment by michaelb** [comment]
Relevant fixes are in the `dev` branch, you can check them out if you want. 

Example if you're using packer:
```
 use {
        "michaelb/sniprun",
        branch = "dev",
        run = "bash install.sh"
    }
```
I'll release a stable v1.2.3 version beginning of next week should no reports of somehow still buggy behavior get reported

**Comment by qvieth** [comment]
Thanks, it works!
