### ISSUE TITLE
Neorg support

### ISSUE THREAD

**Issue by jaschenb** [michaelb/sniprun#189]
**Describe the language you want support for (compiler, specificities)**
Support for [https://github.com/nvim-neorg/neorg](url) similar to org mode

**Support Level to achieve**
Same as org mode

**Additional context**
I just saw the support to run org mode blocks and I just checked the code for the interpreter and it seems to support the neorg file format it should work exactly the same way. Would this be a lot to implement and if you don't have time to do it yourself, could you point me to any other places I may have to change stuff, so I could try to get this working for myself?

**Comment by michaelb** [comment]
The `use_on_filetypes` configuration key, available for every interpreter can be used to force an interpreter to accept other filetypes.

There's an example in the configuration section of the [docupentation](https://michaelb.github.io/sniprun/sources/README.html#configuration)

(Or maybe I didn't understand your issue)

**Comment by jaschenb** [comment]
It's very similar. The only difference I see on first glance is that the code blocked are defined as:
```
@code python
Some code
@end
```

So what I figured is I can basically just copy the code for the org mode interpreter and change the string for the identification of the code block and the filetype?
I just don't know if I need to include this filé somewhere 
Thanks for the quick response

**Comment by jaschenb** [comment]
Thank you so much! I will look into it over the weekend and will give an update here

**Comment by jaschenb** [comment]
Okay I was playing around with it a bit and I guess most of it works. I will just ask the neorg people a little bit more about the specification because so far I haven't found a name tag like in the org mode example, so I just commented that out for block execution. Also I still need to test the Repl feature. Should I submit a PR for this so I can link this to them or can I create a branch on the repo?
Sorry I never contributed to some open source repo like this, so I don't know the usual process 😅

**Comment by michaelb** [comment]
Nice :-)

> I haven't found a name tag like in the org mode example

What do you mean? It may be unimportant... or not


> Also I still need to test the Repl feature.

No need as 'literate programming' languages like markdown or orgmode, and presumably neorg, inherit the interpreter for the bloc's languages which features or not REPL-like capabilities. (But there is nothing to do on the neorg' interpreter side)

> Should I submit a PR 

Yes, the usual process is to open a PR from your forked repo to this one (called 'upstream' repo). Only I have the permission to create a branch on this repo.

Once you've submitted your PR, there will be with some back-and-forth with comments and commits, and once everything's right it'll be merged into the main branch. 

Sniprun is often distributed as a binary, so I'll have to do a new release, nothing to bother you about but there might be a small delay between the merge and neorg support being available for everyone

**Comment by michaelb** [comment]
1: Possible via a little highjacking of the cli args (and since it's unlikely you would ask for argv/argc in a code snippet, it's mostly harmless). Sniprun supports cli arguments when explicitely supported in the interpreter, and only for `:%SnipRun <argv[1]> <argv2> ...  ` commands. You can set check_cli_args to always return ok in Orgmode, (document that the real cli args will get ignored though). Then, given a cli argument, you could do walk the whole selection like done currently and only have the code bloc with a matching name run. I'm noticing there is an issue with running several orgmode code blocs in one visual selection (a crash), hopefully it's at a later stage ( displaying :-/ ? ) and you can successfully run only one of these code blocks. The markdown interpreter GFM_original works as it should for several code blocs per visual selection.


2: Not really, sniprun began developpment when treesitter was more bark than bite and was not deemed useful enough. Nothing is impossible but even I would have trouble.


3: Yes :-) Any option name is ok and will be forwarded from the config

```
require'sniprun'.setup({
    interpreter_options = {
        Neorg_original = { 
            the_option_name_you=_want = "yes_end_of_block_please"
        }
    }
})
```

to the interpreter by simply calling get_interpreter_option(data, "the_option_name_you_want"). It returns a neovim_lib::Value though, so you will have to unpack it as string (or as whatever) yourself. Many interpreters have custom options, feel free to copy-paste. 

While getting the option is easy, displaying on the end of the code bloc is a little bit more complicated. (aka not cleanly possible from the interpreter code. The simplest thing would probably to `return Err(SnipRunError:ReRunRanges(vec![range_start,; range_end]));` and pray about not triggering the bug I talked about in 1.

4: That's something I never really thought about, since in the general case users wouldn't want their cursor moving on its one (think about the case where the code takes an undefinite time to run). So I don't have any  ready-made solution, but the |neovim library](https://docs.rs/neovim-lib/latest/neovim_lib/) I use may allow such things. There's a handle to the neovim session we already use on the first line of code of get_filetype_of_embbeded_code we can maybe use to send cursor events.

**Comment by michaelb** [comment]
hello, any update ?

**Comment by jaschenb** [comment]
Hey hey! Really sorry I didn't reply for so long, but I had stuff at work coming up, that needed to be done. I have this and next week left and then I have 3 weeks off and then I will finish everything.

**Comment by michaelb** [comment]
No worries, take care of yourself!

**Comment by michaelb** [comment]
Sup', it's been ... quite some time, so I think I'll finish this myself by March, save for activity from your end. I'll do my best so github still recognize you as contributor, but I can't promise that and neither that whatever I end up making will fit your needs perfectly. Feel free to open an issue then.
