### ISSUE TITLE
`../sniprun` is not executable

### ISSUE THREAD

**Issue by PorcoRosso85** [michaelb/sniprun#211]
**Describe the bug**
`../sniprun` is not executable

**To Reproduce**

1. install rustup to nixos
2. install cargo and rustc with rustup
3. install sniprun as below

**Expected behavior**
execute sniprun

**Screenshots**
<img width="1157" alt="スクリーンショット 2023-03-03 9 47 27" src="https://user-images.githubusercontent.com/40359643/222603667-7f75ddf5-ba17-487f-9699-c7457e396210.png">
<img width="1157" alt="スクリーンショット 2023-03-03 9 42 48" src="https://user-images.githubusercontent.com/40359643/222603672-a390ee44-7535-42f6-b6d5-2de54942be6a.png">

**Environment:**
 - Neovim version 0.8.1
- OS/distribution nixos

**Additional context**

**Comment by michaelb** [comment]
`:checkhealth sniprun` might provide welcome additional information

Linking old nixos issues here so I don't forget https://github.com/michaelb/sniprun/issues/137

**Comment by PorcoRosso85** [comment]
I'm so sorry to forget use `checkhealth`.
<img width="1157" alt="スクリーンショット 2023-03-03 20 22 36" src="https://user-images.githubusercontent.com/40359643/222707964-a3bb5d86-6f42-4e12-a54e-bcabb226f159.png">

I'll check #137 and #107

**Comment by PorcoRosso85** [comment]
Is there the case that binary cannot be found despite installation is done?

**Comment by michaelb** [comment]
Then I suspect the installation _hasn't_ been done

It can happen when a plugin manager installs the plugin (but this fails because no internet / no rust toolchain), then you restore connectivity / install rust. Most plugins manager won't update or reinstall the plugin even if you tell them to because they think everything is up to date.

A common fix would be to remove the plugin, ensuring the path to the repo sniprun ( you see that in your first error ) doesn't exist anymore, and then installing again.

There may be nix shenanigans and I'm not familiar with that, so the 'manual' way would be to to `cargo build --release` (equivalent to the `bash./install.sh 1` you should have in your plugin manager's config) from sniprun's repo

**Comment by PorcoRosso85** [comment]
<img width="1552" alt="スクリーンショット 2023-03-04 18 11 07" src="https://user-images.githubusercontent.com/40359643/222889040-88bd3cd6-2e22-41e7-918a-3bf87f91ccd1.png">

I've done these:

1. `rm -r $HOME/.local/share/nvim/plugged/sniprun/`
2. re-install plugin ( with vimplug )
3. `cargo build --release` in cloned your repo   ->  unsuccess
4. `sh $HOME/.local/share/nvim/plugged/sniprun/install.sh 1`  -> unsuccess

Is there suspected item to check else?

**Comment by michaelb** [comment]
Well that's kind of a first time sniprun doesn't work _this much_. And I've had NixOS users who succeeded, so this has no reason to not be doable.

Since the binary is reported to 'crash at start' (checkhealth) but also appear to be compiled successfully, I'm very curious about what happens if you just ... run it.

` $HOME/.local/share/nvim/plugged/sniprun/target/release/sniprun`

The normal behavior would be to display nothing, and block the terminal until ctrl-c (waiting for rpc communication that won't happen). Maybe we'll have a useful message there.
If there's nothing, maybe we could try to get the backtrace (`export RUST_BACKTRACE=1`) or run it through debugging tools.

**Comment by AngerM** [comment]
Seeing similar issues in the latest MacOS. Looks like sniprun is failing to build but `install.sh` ignores the failure. If I try to `cargo build --release` manually I see:
```
$ cargo build --release
error: failed to determine package fingerprint for build script for sniprun v1.2.12 (/Users/matt.anger/.local/share/nvim/lazy/sniprun)

Caused by:
  failed to determine the most recently modified file in /Users/matt.anger/.local/share/nvim/lazy/sniprun

Caused by:
  failed to determine list of files in /Users/matt.anger/.local/share/nvim/lazy/sniprun

Caused by:
  failed to open git index at /Users/matt.anger/.local/share/nvim/lazy/sniprun/.git/

Caused by:
  invalid data in index - calculated checksum does not match expected; class=Index (10)
```

**Comment by AngerM** [comment]
I tried deleting and recreating the git repo, doing a `git reset --hard origin/master`, all still exhibit the issue. I've tried both latest stable and beta rust toolchains:
```
cargo --version
cargo 1.69.0-beta.1 (9880b408a 2023-02-28)
```

**Comment by michaelb** [comment]
It doesn't look like the same issue exactly. @PorcoRosso85 is able to compile the binary, at least. (@PorcoRosso85 , what happens if you directly run the binary from the command line ???)

I don't know what kind of ninja mutant computer can produce your error @AngerM and google is not very talkative about this one. I'm (of course-wouldn't be fun otherwise) not able to reproduce this, be it on stable (1.68), beta (1.69) or nigthly (1.70), _from_ the repo auto-cloned by my package manager (packer). 
You could always try to clone this repo independently and compile there (and if it still fails, delete the .git/ folder ?)

**Comment by AngerM** [comment]
Super weird. Had it happen on multiple different machines all with the same error. Doing
```
$ mv .git .gitbackup
$ cargo build -r
$ mv .gitbackup .git
```
seems to allow it to build?

**Comment by PorcoRosso85** [comment]
Hi.
It worked, thank :)

**Comment by michaelb** [comment]
> It worked

What worked, and what did you do ? Is your original issue solved ? 

I'm a little in the dark here, and while I'll gladly document more comprehensively the install procedure on NixOS, I could use some help

**Comment by PorcoRosso85** [comment]
Is it ok that what I tell you as follows is by my lazy memory?

**Comment by michaelb** [comment]
Sure (always better than nothing)

**Comment by PorcoRosso85** [comment]
there are some choice to use cargo

1. not use nixpkgs
2. use nixpkgs for rustup, and then install cargo using rustup
3. use nixpkgs for cargo itself

if choose 1
maybe nothing is different to other users

if choose 2 or 3
cargo won't create $HOME/.cargo
so, anyone has to configure the path of cargo themselves
I choosed 2


nixos user maybe have to choose this way:
https://michaelb.github.io/sniprun/sources/README.html#or-install-sniprun-manually

but, as @michaelb  told me as below in this issue, some tasks are required

if we add more info to your documentations for stupid user like me, 
for example

```before
or install sniprun manually
I trust you know how to add a plugin to the runtimepath, just don’t forget to run ./install.sh, or alternatively, cargo build --release to fetch/build the binary.
```

```after
or install sniprun manually
I trust you know how to add a plugin to the runtimepath, 

- just don’t forget to run ./install.sh, 
- or alternatively, cargo build --release to fetch/build the binary
  - copy binary to neovim data path, such as ' $HOME/.local/share/nvim/plugged/sniprun/target/release/sniprun'
```

**Comment by PorcoRosso85** [comment]
@michaelb 
I can request a PR if you accept this doc's change


And certainly if there was a little more output in install.sh, I might not have asked the question here either.
When I have more time and further thought to organize, I will suggest a little output as well, if @michaelb is open to it.

**Comment by michaelb** [comment]
Hey, I updated the [documentation](https://michaelb.github.io/sniprun/sources/README.html#or-for-nixos-users) to better explain how to install sniprun on NixOS

You're welcome to suggest improvements to the install script verbosity if you want to
