### ISSUE TITLE
macOS  apple ,can not  compile sniprun

### ISSUE THREAD

**Issue by rileychc** [michaelb/sniprun#219]
**Describe the bug**
cd ~/.local/share/nvim/site/lazy/sniprun
bash install.sh
Runnning Sniprun Installer
Looks you are not running Linux: Mac users have to compile sniprun themselves and thus need the Rust toolchain
Compiling sniprun locally:
Building sniprun from source...//it stop in this about 2 hours.

**Screenshots**

<img width="977" alt="截屏2023-03-20 19 19 27" src="https://user-images.githubusercontent.com/116857974/226329091-89d1bed0-eb73-4902-950b-61a46b80d462.png">

**Environment:**
NVIM v0.8.3
macOS 13.2.1  -apple     ,isn't intel
iterm2 Build 3.4.19
xterm-256color

**Comment by michaelb** [comment]
Hmmm quite strange

The message itself is normal, since you're on mac, non-x86 sure but still

I assume `: checkhealth sniprun` doesn't have any interesting info?

Sniprun has been reported to work correctly on M1 (and presumably M2) Apple devices, so I'd be curious of the output of `cargo build --release` run from a clone of this repo (clone manually or use the clone from your package manager)

**Comment by rileychc** [comment]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/116857974/226338674-d94e27bf-624e-4c6c-a918-7d7fe623d089.png">
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/116857974/226338737-52dab607-335d-4340-8f57-d15c43ff9bfe.png">
