### ISSUE TITLE
Cpp Compile-Time Error

### ISSUE THREAD

**Issue by mrPuckk** [michaelb/sniprun#268]
Hi there, I got an issue when using `std::vector` in Cpp with Sniprun. (g++ compiler)

**Describe the bug**
I am encountering a compile-time error when using vectors declared in C++. The compiler I am using is g++ that set in Sniprun setup. 

**To Reproduce**
I'm experiencing a compile-time error only when using Sniprun with code snippets that involve vectors having predefined elements. However, if the vector is declared in the same format without initializing its elements, the code runs smoothly. 
` std::vector<int> myVector{ 5, 10, 15 }; //Got Compile-time Error 
`
` std::vector<int> A; //Run smoothly 
`
Or even I tried a case: `std::vector<int> A(5, 10);`, it still runs smoothly. 

**Screenshots**
<img width="786" alt="Screenshot 2023-12-28 at 9 45 13 am" src="https://github.com/michaelb/sniprun/assets/121914195/05e632f3-8e7c-4c0f-8ec9-c994f41edeb1">

**Environment:**
 - LunarVim
-  Macos

**Comment by michaelb** [comment]
Hi,
I configured my sniprun instance to run g++ but haven't encountered the issue you mention...

`std::vector<int> v {8,4,5,9};` don't fail with 'Compile-time error', and neither do variants (with v = {...}, v; with/without spaces).

Does your code snippet compiles fine outside of sniprun ? I have a fairly recent g++ version, so it may be due to that ..?
In any case, you can check sniprun's log at $XDG_CACHE_HOME/sniprun/sniprun.log (often ~/Library/Caches on MacOS I believe)

**Comment by michaelb** [comment]
Closing, assuming your problem doesn't bother you anymore
