### ISSUE TITLE
(no output) for elixir file

### ISSUE THREAD

**Issue by cassepipe** [michaelb/sniprun#288]
Trying to evaluate a line in a elixir (`.ex` or `.exs`) file shows `(no output)`

```
echo "x = 42" > file.ex1
lvim -c "normal V" -c ":SnipRun" file.ex 
```

I expected a `42` as `iex` would output

The plugin is functional and has the expected behaviour for a python file

LunarVim 1.4 
Fedora 40

**Comment by michaelb** [comment]
iex is the REPL interpreter for Elixir right ? Sniprun uses iex when the REPL mode is enabled in for elixir ( `repl_enable = {"Elixir_original"}` ), in which case your example _does_ output 42.

Otherwise, sniprun uses `elixir` under the hood, which _doesn't_ outputs 42 when it runs a file containing the shown code..

**Comment by cassepipe** [comment]
Haaa it all makes sense now. Thanks for taking the time to reply. (And for crafting this plugin)
