### ISSUE TITLE
Support specifying what commands to use for compiling stuff

### ISSUE THREAD

**Issue by YaBoiBurner** [michaelb/sniprun#68]
**Is your feature request related to a problem? Please describe.**
Right now, (as far as I can tell) compilers are hard-coded to `gcc`, `g++`, `go`, etc. In some cases, this means that someone would need to install a different compiler than the one they're already using for this plugin to work.

This could also allow for using a compiler cache like `ccache` or `sccache` so things run a little faster (but that's not as important)

**Describe the solution you'd like**
An option to specify what compilers to use.

**Describe alternatives you've considered**
All I've got right now is changing the hard-coded values in the source code, and then building from scratch.

For C & C++ specifically, the default compilers could be changed to respect the `$CC` & `$CXX` environment variables respectively, and default to `cc` and `c++` respectively. Those are arguably safer if it stays hard-coded.

**Comment by michaelb** [comment]
You are totally right, that should be an option,   but it's not as simple as you would think:


- all compiler don't have feature parity (for example, only gcc allows functions definition inside of another function)
- the output on different compiler/interpreters (on compilation or runtime errors) might be too different to properly display a message: I rely heavily on the fact that gcc provide a meaningfull message on a particular line of its otherwise undereadably long output

That being said, gcc/clang is a bit of a corner case and most other languages will benefit from this idea at no cost. I see some way of doing that, and it could have been complicated but boy I'm happy to have thought ahead: I see a relatively straightforward way of achieving something satisfying
