### ISSUE TITLE
support for older versions of glibc than 2.33

### ISSUE THREAD

**Issue by aMOPel** [michaelb/sniprun#78]
**Is your feature request related to a problem? Please describe.**
:Sniprun silently fails so i tried to run the binary just like that and get:
./sniprun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./sniprun)
./sniprun: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./sniprun)

**Describe the solution you'd like**
im on ubuntu 20.04 and the libc version is 2.31, can you add support for older versions of libc?

**Describe alternatives you've considered**
if not, at least add it to the dependency list

**Comment by michaelb** [comment]
alright, that's probably due to the precompiled binary being compiled on a very up-to-date machine, or alternatively that may be a bug caused by an older issue, that is resurfacing because you're using neovim v0.4.x (that limit the sniprun version to v0.4.9 and newer fixes are not backported). 

The requirement for a 'newer' libc is something that has to do with Rust or one of my dependencies, I don't have much say over that

I suggest you compile sniprun locally, by adding '1' as argument to the post-install script:
'bash ./install.sh 1'. Mind that you will need to have the rust toolchain installed.

**Comment by aMOPel** [comment]
i read about that in other issues but i really dont want to install rust just to compile this plugin.

btw i am on nvim 0.5

**Comment by michaelb** [comment]
Sadly, I'm only by myself here. I only have one machine, and 'i really dont want to install ubuntu 20.04 just to compile this plugin for you' , sorry but that's not gonna happen, I value my time as much as you value yours.


Trying to find a solution, but there's not much I can do....

Your being on nvim 0.5 simplify things; and I have relatively good news. If you compile once, but don't want to keep the Rust toolchain installed (perfectly understandable, it's like 400MB), you can remove it _along with the post-install script_. If there is no post-install script specified, updates will never overwrite your binary, and should never break the functionnality of the plugin. You'll be stuck on the current version though.

**Comment by michaelb** [comment]
For now i'll take on your suggestion to add that as a dependency :-)

**Comment by aMOPel** [comment]
how about this:
https://users.rust-lang.org/t/how-to-compile-rust-with-a-specific-glibc-version-for-gnueabihf-architecture/6680/4
leading to
https://hub.docker.com/r/alexcrichton/rust-slave-linux-cross/

**Comment by rekaerst** [comment]
You could set up Github Action to publish the binary for the older version Glibc automatically. 2.33 is a too bleeding edge version for most people.

**Comment by michaelb** [comment]
yeah, but how ? Plus, I have to be sure that the binary would still be compatible with the 'bleeding-edge' people, or it would break their setup.

(or modify the install script so that there are 2 binaries to intelligently choose from)

As I said before, that's above my github action competences. I promise to have a try but I can't promise it will be successsfull

**Comment by rekaerst** [comment]
> (or modify the install script so that there are 2 binaries to intelligently choose from)

IIRC glibc is backward-compatible, not forward-compatible. Running binaries that were compiled for an older glibc version will run fine on a system with a newer glibc.

Anyway thanks for the awesome plugin. I wish I could help.

**Comment by aMOPel** [comment]
> @aMOPel is this satisfying/even working? (an update will not download this latest release 0.5.6 if you're not on the 'dev' branch, until the PR is merged)
> 
> It's still ok on my machine with a binary compiled from github action (ubuntu 20.04) that _should_ also be compatible with older GLIBC

yes it is working indeed thanks very much :) was it hard to do with github action? i have no experience with it
