### ISSUE TITLE
sniprun binary incompatible or crash at start in c or cpp files

### ISSUE THREAD

**Issue by phuongortheeast** [michaelb/sniprun#81]
**Describe the bug**
sniprun won't work in c files, when I run `checkhealth sniprun` every thing was fine except the error mentioned. I tried compiling the plugin locally, reinstalling language server and compiler but the issue persist.

**To Reproduce**
Execute sniprun in a .c or .cpp files

**Expected behavior**
Output of my code or `<- (no output)` in empty line

**Environment:**
 Lunarvim  (NVIM v0.5.0-dev) in Artix Linux

**Additional context**
The bug only happen in .c (.cpp) files, python works normally

**Comment by michaelb** [comment]
Thanks for reporting.

I'll have a look asap, but i'm afraid that may be environment-specific. I'll come back soon with more info

**Comment by michaelb** [comment]
Okay, I could test locally and, sure enough, sniprun works on C and C++ files. I'll assume 

Because you say it works on Python files, I assure you that you don't have to reinstall anything. Though the fact that the checkhealth does this false error is worrisome, it's not _impossible_ that the check might fail when sniprun works correctly, it's geared towards _always_ failing if sniprun doesn't work at all.

Could you provide copies of the file at ~/.cache/sniprun/sniprun.log (or your XDG_CACHE location):
- after a `checkhealth sniprun`
- after you've run a simple snippet of code for c or cpp, such as `printf("hello\n");"

Also, could you check if next to the log there are directories with the name of C an Cpp interpreters, containing the last snippets of code you sent to sniprun + boilerplate wrapped around (if so try to compile the source file). whatever happens should appear in the log file anyway, but I prefer to ask.

Also, did you configure anything through the interpreter_option key?

**Comment by phuongortheeast** [comment]
After cd into `.cache/sniprun`, I found a bunch of junk file that I then deleted. After that, sniprun works normally again but checkhealth still show the error so I guess you are right. Yes, there are c_original file in the cache and the deleted file didn't output anything.
Thank you for your help!

**Comment by michaelb** [comment]
Okay, I'll keep in mind that this can happen (probably under very specific / crashy situation)

FYI, in the future if that happens again trash stuff (in fact ,the whole .cache/sniprun/)can be cleaned with `:SnipReset`
