### ISSUE TITLE
Support for Mathematica

### ISSUE THREAD

**Issue by physicophilic** [michaelb/sniprun#83]
**Describe the language you want support for (compiler, specificities)**
I'd like an interpreter for Mathematica/Wolfram Language that uses interpreter and works with filetype `mma`. 

**Support Level to achieve**
Bloc level should be enough for me!

**Additional context**
I can call `wolframscript` from terminal to run a small chunk of code, but the process is slow when this is done from vim, especially because I use python based UltiSnips to do it for me. I guess using sniprun's method it can be way faster?

**Comment by michaelb** [comment]
That should be doable without much issues (in fact, if you're a bit familiar with Rust, that should even be possible to do yourself). Is there any licencing/pay-for trouble I should be aware of beforehand? (I can't really pay a licence just to check everything works... and keep working in the CI pipeline, ideally)

I'll have a look when I have some free time, that should be no later than by next week, but i'm not making any commitment here.

Sniprun is indeed way faster than other alternatives (and I've received this feedback from users), but usually the overhead is unnoticeable - or is it just my impression since I'm using sniprun ? - in comparison to the time it take to launch a new interpreter/compile (jupyter kernels are sooooo slow!), and run your code. Overall, it's as fast as it gets.

**Comment by physicophilic** [comment]
Thanks Michael.

I don't know any rust myself. I am only an average end user with scientific programming experience.

> Is there any licencing/pay-for trouble I should be aware of beforehand? (I can't really pay a licence just to check everything works... and keep working in the CI pipeline, ideally)

Yes, there is a bit of trouble.  A free trial of 15 days is available for Mathematica, but otherwise it is an expensive software. 
Usually schools gives it to students these days (like I got from mine). I absolutely won't have you paying for it though. If you can't do it, I will try harder. 

> I'll have a look when I have some free time, that should be no later than by next week, but i'm not making any commitment here.

Yes, sure, that sounds good.


> Sniprun is indeed way faster than other alternatives

Yes, I also find that. On top of it there's massive convenience in usage, which is arguably more important,  
especially if the speed increase isn't noticeable.

**Comment by michaelb** [comment]
Nice, 15 days sound long enough to make something decent, however if someone reports issues next month then i'll have a problem but whatever.

I'm still a (CS) student myself but i don't think my school grant a free licence for that, i'll have a look

**Comment by michaelb** [comment]
I've rarely worked  with something so "closed" so I'm probably missing some things here and there.

The latest commit on dev should bring mathematica bloc-level support; but with several caevats:

- A new Mathematica kernel instance is started at each snippet sent to sniprun (and those are sloooow, so there is a noticeable delay). I hope I can manage doing a opt-in REPL (connecting to an existing kernel) that would both solve this and provide a very nice experience, almost jupyter-like, but first let's check that what I did up to now is in line with your expectations.

- Graphics (Plot[]) produce no output!! It looks like 4Go is too small to include a simple X-window manager (satire)

I'd like your opinion on the latter if possible. Important, not important? Let the user 'sniprun' modified Plot[] instructions, assuming they face the same issue anyway when running their script, or hackily wrap Plot[] calls with an Export -> file.png and the xdg-open  the file? Or maybe there's another hack you can tell me about

Also, just to be sure, could you confirm the filetype (`:set ft?`) from a mathematica file is 'mathematica'? 

To install the dev version, you should point your plugin manager on dev and use 'bash install.sh 1' as installation script (you'll need the rust toolchain to compile sniprun); example with vim-plug:
 `Plug 'michaelb/sniprun', {'do': 'bash install.sh 1', 'branch':'dev'}`

**Comment by physicophilic** [comment]
Okay, great. I have tested it and here is what I have found. 



>    A new Mathematica kernel instance is started at each snippet sent to sniprun (and those are sloooow, so there is a noticeable delay). 

Sniprun is about 2-3 times faster than my UltiSnips implementation. Trouble is that it gives 'no output' on everything I have tried, like this:

```mma
Integrate[Sin[x], {x,0, Pi}] <- (no output)

Integrate[Sin[x], {x,0, Pi}]  (* using UltiSnips *)
2

```

> I hope I can manage doing a opt-in REPL (connecting to an existing kernel) that would both solve this and provide a very nice experience, almost jupyter-like

That would be beyond amazing. But I am not expecting it because mathematica often disappoints because of the closed nature. Or maybe it is because my software powers are very limited.

>    Graphics (Plot[]) produce no output!! It looks like 4Go is too small to include a simple X-window manager (satire) I'd like your opinion on the latter if possible. Important, not important?

Right. I hate that; my implementation produces no graphics either. I think it would be awesome to have the xdg-open + Export wrap around Graphics. Maybe you can just provide an example of how the user should do the wrapping rather than shipping it by default? One might export to `/tmp` but that's like increasing complications. 

A second way to see graphics exists which may be helpful. Here it is:
```mma
<<JavaGraphics`
(*pause for loading*)

Plot[Sin[x], {x,0, 2Pi}]
```
when called from the REPL `math` or `wolfram` in the terminal will open a graphics app with the plot.  

> Also, just to be sure, could you confirm the filetype (:set ft?) from a mathematica file is 'mathematica'?

Well, `set ft?`'s output is `mma` which mathematica goes by I think.. Is that related to way I don't see the `output`? I had forcefully `set ft=mathematica` but still got `no output` though.


Let me know what I should do.

**Comment by physicophilic** [comment]
Ah, I got the output. I see that 

```mma
Print[Integrate[Sin[x], {x,0, Pi}]
```
is needed. I think it would be important to wrap `Print[]` around the code by default.

**Comment by michaelb** [comment]
> Well, set ft?'s output is mma which mathematica goes by I think.. Is that related to way I don't see the output? I had forcefully set ft=mathematica but still got no output though.

`mma` is fine too; I (hard) coded the mathematica interpreter to reply to filetypes 'mathematica' or 'mma', but as my neovim setup doesn't recognize the file extension, it doesn't set the filetype, and I didn't know what filetype was provided, surely through a plugin... Well if it's either it's ok.

> I think it would be good to wrap Print[] around each line in the code by default.

That may cause problems, if mathematica has multi-line statements or something i'm not aware of... You don't want to wrap Print[] around a for loop statement I guess (is there any such thing in mathematica?). I don't want to make it a default, but I can manage **configurable behavior** like either of:

1. For each line that doesn't contain a print statement, and doesn't end with ';' or some other symbol that indicate this is not an expression like [ or }, wrap the line with Print[]
2. Wrap the last line of the code snippet with Print[] if it doesn't contain a Print[] or ends with ';'

Something more complicated (like parsing mathematica to retrieve full statements/expressions and wrap them individually) won't be possible with my current skill and more importantly the non-existant mathematica spec&documentation. 

BUT

If I can connect to a mathematica kernel, and use it 'the REPL way', this behavior may become a unintentionnal but welcome side-effect. There's hope in my opinion.

> So maybe this is a question of philosophy? What philosophy do you prefer?

I like better keep sniprun script-like: because that's how it works under the hood, so changing it may create very different behavior, and may not be possible with each language. Right now, I can assert, that, boilerplate like `int main (){ .... }` apart, the code to sent to sniprun is executed just like it would if you copied the snippet to a separate file and compiled/ran it.

> Sniprun is about 2-3 times faster than my UltiSnips implementation.

Great! but still to slow, but I will definitively try to implement the REPL thing

**Comment by physicophilic** [comment]
Yes I also agree with you. Script should be treated the way you've made it. The configuration option 1 was what I meant. Even 2 sounds good enough. For plotting 3 is great. 


Yes, REPL would be awesome!

**Comment by michaelb** [comment]
oh my god. It [REPL] works. And if you though the first implementation was fast, oh boy I have good news (there is basically no latency just like if you were using directly the mathematica REPL).

I need to polish a few things up, document some hacky hacks, and i'd like to try replicating what I've done with another interpreter (to avoid making 5000 releases this week and to detect any problems such as race conditions etc...). Should not be too long before I can make it available to you and the wider community.


On the other hand, I now hate Mathematica and anything that has to do with it. I hope you can find better stuff to do your job someday, and that my plugin won't make you stick with this language and interpreter for longer that you would need to.

**Comment by physicophilic** [comment]
Damn, this is great Michael.

It does work. It is awesome. Just been testing the REPL mode, its super fast, and Plot works perfectly with `;`. I also checked the non-REPL mode. It works just as you describe; I tried `wrapping_last_line_with_print = 1`.

So the only things which are a bit odd (but I don't really mind) are the REPL mode `;` after Plot and rerunning the first snippet. 

> On the other hand, I now hate Mathematica and anything that has to do with it. I hope you can find better stuff to do your job someday, and that my plugin won't make you stick with this language and interpreter for longer that you would need to.

Haha! What happened?   

To be honest, Mathematica is a great software for symbolic calculations, but pales in most other aspects, particularly customization. I largely use it for simplifying my results and doing quick integrals. Otherwise I use julia/python. Most theoretical physicists find it useful, and currently the best open alternative to it is SymPy (quite slower/has a lot less features; still lovely in many ways). In fact, many folks are happy with Mathematica notebooks; some of them even do their LaTeX in it as well. For me that's the deal breaker. I can't write in that thing.

Thanks a lot Michael. 

I have one more question. Can I yank the contents of the output somehow? Maybe enter into the floating window and then yank directly like for LSP hover window, or yanking virtual text.. I guess neovim may have provided something to do that?  Sometimes outputting the result as

```mma
ToString[Integrate[Sin[x] Cos[x], x], TeXForm]
```
it can be directly pasted in another vim buffer.

**Comment by michaelb** [comment]
> So the only things which are a bit odd (but I don't really mind) are the REPL mode ; after Plot and rerunning the first snippet.

I agree re-running the first snippet is a bit odd, but tha'ts due to very obscure shenanigans with unix, fifo (named pipes), background processess/dameon and I can't do much better.  
Since it's only about running sniprun once (there is no need to send anything meaningful) before being able to run send code to the mathematica repl; maybe you could configure an autocmd to run :SnipRun everytime you open a .mma file?

> Can I yank the contents of the output somehow?

I don't know if you can do that yet, I've not tried yet, but you should open a different issue and I'll see what I can do. If you're an advanced vim user you may be able to figure out something if I tell you sniprun 'echomsg' text into the command area. I'm not expert myself but there may be ways to get back the contents of a previous echomsg... maybe

> Haha! What happened?

Though I didn't dwelve into the language itself (or any of its advanced capabilities) I found the ecosystem awful, (closed mentality, imprecise documentation, almost 'imposed' editor, fricking interpreter told me several times that my free licence had expired for no reason ...). 
I just don't like that to the point I would relate to people getting frustrated over those points.

**Comment by physicophilic** [comment]
> maybe you could configure an autocmd to run :SnipRun everytime you open a .mma file?

Sure, I think that's not an issue. 

I see, I will check on `echomsg` and if I can find a simple way I will add it here. 

Oh wow, the interpreter is sure going crazy to announce the expiry like that. Yea.. hate that its closed. Makes so hard to use it in a custom way. Thanks for putting up with it!

**Comment by michaelb** [comment]
>  At that time though one can also look at literal backslashes being outputted as \\.

Okay, I did miss that. Though, I don't know where it comes from.... The REPL itself has not this issue, and another (python) interpreter built around the same core scripts mathematica uses doesn't have this issue as well, so it's not something sniprun-wide. If I can fix it before my licence expires, good, if I can't, so be it...

**Comment by michaelb** [comment]
> Latex ..stuff... I can't write in that thing.

Just thinking, if you're more of a markdown guy, there's a markdown interpreter in sniprun (GFM_original) that can [be configured to] have interactive code snippets just like in source code, while writing a markdown file.

And lastly, don't forget to get back on the stable branch once 0.5.8 is released :-)

**Comment by physicophilic** [comment]
So.. I've got sort of a problem. I started using this interpreter regularly, and realized that Mathematica gets really angry on relaunching, and this ends up happening often. It stops working after a few tries, and I can't fix it myself after that. Institute people enter the license to fix it. 

Whenever I leave the mma buffer it seems to relaunch after I return, and of course during the crashes. I am scared to test it out now worrying it might again do that. Does anything strike you which could be causing this? In the snipinfo you've written it works only for one mathematica buffer. Could that be the reason?

If you have any instructions I'll try to test them accordingly.  Each time it relaunches I will try to `pkill` it.

**Comment by michaelb** [comment]
> So.. I've got sort of a problem. I started using this interpreter regularly, and realized that Mathematica gets really angry on relaunching, and this ends up happening often. It stops working after a few tries, and I can't fix it myself after that.

Ok

> Institute people enter the license to fix it.

What does that mean?

> Whenever I leave the mma buffer it seems to relaunch after I return, and of course during the crashes.

That sounds pretty sane. The process shouldn't exist after you exit neovim, otherwise things might conflict with an active instance you could run independently.

>  In the snipinfo you've written it works only for one mathematica buffer.

For one neovim instance. It means you can't have two terminal, with two neovim's opening mathematica files, and expect sniprun to work on _both_ 

>  I am scared to test it out now worrying it might again do that.
Do what ?

> If you have any instructions I'll try to test them accordingly. Each time it relaunches I will try to pkill it.
I don't understand



Could you clarify all these points ?

**Comment by physicophilic** [comment]
> >    Institute people enter the license to fix it.

> What does that mean?

Mathematica asks for license key and a password after certain number of relaunches. I don't have either for my institute's subscription - I can only request them to re-enter the details when this happens. (In fact I screwed up my own mathematica license this way - while I did have license key, I don't know the password. They've not replied yet to my email.)


> That sounds pretty sane. The process shouldn't exist after you exit neovim, otherwise things might conflict with an active instance you could run independently. And if you run something that crashes the mathematica kernel, it would seem natural that the next SnipRun will relaunch a kernel

Yes. I agree with you that after neovim exits process should end, and didn't meant that. 

I was saying it was relaunching within the same neovim process, when I seemed to do things like leaving buffer idle for a while..or when I opened a floating terminal.. or when I used vim mode of alacritty (my terminal) to copy the sniprun's output on buffer. It happened a lot. 



> For one neovim instance. It means you can't have two terminal, with two neovim's opening mathematica files, and expect sniprun to work on both

Okay. Sorry I spoke from memory.


> > I am scared to test it out now worrying it might again do that.

> Do what ?

Relaunch repeatedly to a point where I have to request my institute's service to fix it again. 

> >   If you have any instructions I'll try to test them accordingly. Each time it relaunches I will try to pkill it.

> I don't understand

I know your mathematica has expired now. If there are some specific things you want me to try I can try, while making sure I keep checking that multiple instances of kernel aren't being launched by checking `htop`. Hopefully that might work.

> Could you clarify all these points ?

Sorry for being so unclear!! 

Let me know if something can be done!

**Comment by michaelb** [comment]
I don't really know what I'll be able to do about that, but maybe something will catch my eyes if you're kind enough to provide:

- your sniprun configuration

- neovim version just in case

- the content of `~/.cache/sniprun/sniprun.log` and `~/. cache/sniprun/mathematica_original/log` after a relatively long session (these get overwritten pretty easily if you launch sniprun). If you can't do that, just get me the last ones. Notice: those logs may contain parts of your code, idk if there is any proprietary stuff....

- a short description of what you see in htop when you encounter the issue (how many of what problematic process)

**Comment by michaelb** [comment]
@physicophilic There's recently been an issue ( #117 ) about another REPL interpreter that kept the backend running after neovim exited.

The error was a single forgotten '&' in a bash script that prevented the 'kill after neovim exits' to succeed, but what's interesting is that the bash script is also used by sniprun's Mathematica interpeter


So I wonder if your issue wasn't just that Mathematica didn't like when too many instances were running _at the same time_ ,which should be fixed now

**Comment by michaelb** [comment]
Since still issue has been stalled for weeks, and should be fixed, i'll close it now
