### ISSUE TITLE
Why is `wget` used to download the binary instead of `curl`?

### ISSUE THREAD

**Issue by zeertzjq** [michaelb/sniprun#89]
I think `curl` is always present where `sniprun` is installed because it is required by `git`, whereas `wget` isn't always present.

**Comment by michaelb** [comment]
Because I didn't think of that !

Thanks for bringing this to my attention :-) 

Curl, being indeed a git dependency, (and it's 100% sure every neovim/plugin-manager user has git installed), is obviously a better choice.

I'll change that sooner rather than later, and it won't require a new release (new version etc...) so futures updates will fetch the binary via curl

**Comment by michaelb** [comment]
Changes done, i'll be closing this soon :-)

**Comment by zeertzjq** [comment]
This downloads an HTML document. I guess `-L` is needed. Maybe `-fsSL` is even better. (Without `-s` a progress bar is written to stdout.)

**Comment by michaelb** [comment]
Whooops, should have tested better. Will do so tomorrow

**Comment by michaelb** [comment]
I remember now why wget; 
curl is absolutely a pain to use, it can do so much things it's a mess in the end.


Hadn't you provided the options, I probably wouldn't have found the correct ones (and even now, I'm still half-trusting you because I can't find what -f does on the man page. But it works. Anyway, thanks a lot !

**Comment by zeertzjq** [comment]
> I remember now why wget;
> curl is absolutely a pain to use, it can do so much things it's a mess in the end.
> 
> Hadn't you provided the options, I probably wouldn't have found the correct ones (and even now, I'm still half-trusting you because I can't find what -f does on the man page. But it works. Anyway, thanks a lot !

```
       -f, --fail
              (HTTP)  Fail silently (no output at all) on server errors. This is mostly done to enable scripts etc to better deal with failed attempts. In normal cases when an HTTP server
              fails to deliver a document, it returns an HTML document stating so (which often also describes why and more). This flag will prevent curl from outputting  that  and  return
              error 22.

              This  method  is  not fail-safe and there are occasions where non-successful response codes will slip through, especially when authentication is involved (response codes 401
              and 407).
```

**Comment by michaelb** [comment]
Ahah thanks, I guess my search skills aren't up to the challenge (-f had too many entries, -f<space> not enough).
The last commit pushes your suggestion into the install script :-)
