### ISSUE TITLE
Passing command-line arguments, when running whole file like :%SnipRun {args}

### ISSUE THREAD

**Issue by DipeshChouhan** [michaelb/sniprun#97]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by michaelb** [comment]
Hmm i'll have to think about that

There is surely a way to capture arguments from the vim command line and pass them to the final script/executable _but_:

- may be a bit clunky to use. I mean typing ":%SnipRun arg1 arg2 arg3" each time you want to test something?

- relative path (as CLI argument) _will_ be an issue, because sniprun runs in its own location. This **won't** change but maybe we can hack around with symlinks and stuff

**Comment by DipeshChouhan** [comment]
Is it possible to toggle the feature on or off. If on then only it will ask for arguments.

**Comment by michaelb** [comment]
> Is it possible to toggle the feature on or off. If on then only it will ask for arguments.

I don't think it is necessary: you'd think when there is no arguments after the SnipRun command, then, no args. Otherwise, copy the extra arguments from the neovim command to the (ex in python) `python main.py` command sniprun launches

Or maybe I don't understand what you mean by 'ask for argument'


Your feature request is quite feasible and a good suggestion, though I'll need some time to work on implementation details and making the thing work, especially when the argument is a relative path

Anyway, the more we discuss here, the clearer your request will be :-)
